stages:
  data-cleaning:
    cmd: python -m src.data.data_cleaning
    deps:
    - data/raw/songs-info.csv
    - src/data/data_cleaning.py
    outs:
    - data/cleaned/songs-info-cleaned-content.csv
    - data/cleaned/songs-info-collab.csv
  content-filtering:
    cmd: python -m src.content_based_filtering.content_filtering
    deps:
    - data/cleaned/songs-info-cleaned-content.csv
    - src/content_based_filtering/content_filtering.py
    outs:
    - data/processed/transformed_content_filtering.npz
    - models/transformers.joblib
  collaborative-filtering:
    cmd: python -m src.collaborative_filtering.collaborative_recommendation
    deps:
    - data/raw/user-info.csv
    - data/cleaned/songs-info-collab.csv
    - src/collaborative_filtering/collaborative_recommendation.py
    outs:
    - data/processed/collab_filtered.csv
    - data/processed/track_ids.npy
    - data/processed/interaction_matrix.npz
  transform-filtered-data:
    cmd: python -m src.transformation.transform_filtered_data
    deps:
    - data/processed/collab_filtered.csv
    - models/transformers.joblib
    - src/transformation/transform_filtered_data.py
    outs:
    - data/processed/transformed_hybrid_data.npz
